name: Keycloak Integration CI

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:

  tests:
    name: Jakarta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event_name != 'schedule' }}
      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'schedule' }}
        with:
          ref: 'main'
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Update maven settings
        run: mkdir -p ~/.m2 ; cp .github/settings.xml ~/.m2/

      - name: Cache Maven repo
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/keycloak
          key: cache-1-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-1-${{ runner.os }}-m2

      - name: Get Keycloak
        run: scripts/prepare-local-server.sh

      - name: Build Quickstarts
        run: scripts/build-quickstarts.sh jakarta

      - name: Start Keycloak
        run: scripts/start-local-server.sh

      - name: Run unit tests
        run: scripts/run-tests.sh jakarta

  tests-spring:
    name: Spring
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event_name != 'schedule' }}
      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'schedule' }}
        with:
          ref: 'main'
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Update maven settings
        run: mkdir -p ~/.m2 ; cp .github/settings.xml ~/.m2/

      - name: Cache Maven repo
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/keycloak
          key: cache-1-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-1-${{ runner.os }}-m2

      - name: Get Keycloak
        run: scripts/prepare-local-server.sh

      - name: Build Quickstarts
        run: scripts/build-quickstarts.sh jakarta

      - name: Start Keycloak
        run: scripts/start-local-server.sh

      - name: Run unit tests
        run: |
          mvn -f spring/rest-authz-resource-server -Djakarta clean package verify

  tests-nodejs:
    name: Node.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event_name != 'schedule' }}
      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'schedule' }}
        with:
          ref: 'main'
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get Keycloak
        run: scripts/prepare-local-server.sh

      - name: Start Keycloak
        run: scripts/start-local-server.sh

      - name: Run unit tests
        run: scripts/run-tests.sh nodejs

  tests-js:
    name: JavaScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event_name != 'schedule' }}
      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'schedule' }}
        with:
          ref: 'main'
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get Keycloak
        run: scripts/prepare-local-server.sh

      - name: Start Keycloak
        run: scripts/start-local-server.sh

      - name: Run unit tests
        run: scripts/run-tests.sh js

  tests-extension:
    name: Extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event_name != 'schedule' }}
      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'schedule' }}
        with:
          ref: 'main'
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Update maven settings
        run: mkdir -p ~/.m2 ; cp .github/settings.xml ~/.m2/

      - name: Cache Maven repo
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/keycloak
          key: cache-1-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-1-${{ runner.os }}-m2

      - name: Get Keycloak
        run: scripts/prepare-local-server.sh

      - name: Build Quickstarts
        run: scripts/build-quickstarts.sh extension

      - name: Start Keycloak
        run: scripts/start-local-server.sh extension

      - name: Run unit tests
        run: scripts/run-tests.sh extension

