name: Quickstarts tests

on: [push, pull_request]

jobs:
  tests:
    name: Quickstarts tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: |
          cp -f maven-settings.xml ~/.m2/settings.xml
          .github/scripts/generate-keycloak-json.sh

      - name: Checkout Keycloak repo
        uses: actions/checkout@v2
        with:
          repository: keycloak/keycloak
          ref: master
          path: keycloak

      - name: Cache Maven repo
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/keycloak
          key: cache-1-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-1-${{ runner.os }}-m2

      - name: Build Keycloak dist
        run: |
          mvn clean install -Pdistribution -DskipTests -f keycloak -B
          mkdir keycloak-dist
          find keycloak/distribution/server-dist/target -maxdepth 1 -type f -name 'keycloak-[[:digit:]]*.tar.gz' -exec tar xzf {} --strip-components=1 -C keycloak-dist \;
          keycloak-dist/bin/add-user-keycloak.sh -u admin -p admin

      - name: Build Quickstarts
        run: mvn clean install -DskipTests -B

      - name: Modify Keycloak dist
        run: cp authz-js-policies/target/authz-js-policies.jar keycloak-dist/standalone/deployments

      - name: Start server
        run: .github/scripts/start-local-server.sh

      - name: Archive keycloak.log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: keycloak.log
          retention-days: 2
          path: keycloak.log

      - name: Run tests
        run: .github/scripts/run-tests.sh

      - name: Archive logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          retention-days: 2
          path: test-logs